services:
  postgres-spring-crud:
    container_name: postgres-spring-crud
    image: postgres:12.19
    restart: always
    volumes:
      - .database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret